Add cxx standard to cdash and add conditions on ranges::copy

diff --git a/.github/workflows/ci-container.yml b/.github/workflows/ci-container.yml
--- a/.github/workflows/ci-container.yml
+++ b/.github/workflows/ci-container.yml
@@ -33,17 +33,27 @@ jobs:
           echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
           echo "CCACHE_COMPRESSLEVEL=6" >> $GITHUB_ENV
           echo "CONAN_HOME=${GITHUB_WORKSPACE}/.conan2" >> $GITHUB_ENV
+          echo "CXX=clang++" >> $GITHUB_ENV
+          echo "CC=clang" >> $GITHUB_ENV
+          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
           echo "NUM_THREADS=4" >> $GITHUB_ENV
           sudo -H pip3 install -U conan
 
-      - name: load cache
-        id: cache-restore
+      - name: load build cache
+        id: build-cache
         uses: actions/cache/restore@v4
         with:
           path: | 
             ${{ github.workspace }}/.ccache
+          key: r3b-build-cache-${{ matrix.repos }}
+
+      - name: load conan cache
+        id: conan-cache
+        uses: actions/cache/restore@v4
+        with:
+          path: | 
             ${{ github.workspace }}/.conan2
-          key: r3b-cache-${{ matrix.repos }}
+          key: r3b-conan-cache-${{ matrix.repos }}
 
       - name: configure-build
         uses: './.github/actions/r3bbuild-steps'
@@ -56,21 +66,127 @@ jobs:
 
       - name: ccache stats
         if: always()
-        run: ccache --show-stats
+        run: |
+          ccache --show-stats
+          ccache --print-stats
 
       - name: cache-delete
         run: |
           sudo dnf -y install gh
           git config --global --add safe.directory $GITHUB_WORKSPACE
-          gh cache delete ${{ steps.cache-restore.outputs.cache-primary-key }} || true
+          gh cache delete ${{ steps.build-cache.outputs.cache-primary-key }} || true
+          gh cache delete ${{ steps.conan-cache.outputs.cache-primary-key }} || true
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: save cache
+      - name: save build cache
         uses: actions/cache/save@v4
         with:
           path: | 
             ${{ github.workspace }}/.ccache
+          key: r3b-build-cache-${{ matrix.repos }}
+
+      - name: save conan cache
+        uses: actions/cache/save@v4
+        with:
+          path: | 
             ${{ github.workspace }}/.conan2
-          key: r3b-cache-${{ matrix.repos }}
+          key: r3b-conan-cache-${{ matrix.repos }}
+
+  clang-format:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: cpp-linter/cpp-linter-action@v2
+        id: linter
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: 'file'  # Use .clang-format config file
+          tidy-checks: '-*'
+          version: 18
+          verbosity: debug
+          lines-changed-only: false
+          files-changed-only: false
+          step-summary: true
+          thread-comments: 'false'
+          extensions: 'h,cxx'
+          ignore: '*|!neuland|!r3bbase|!r3bdata/neulandData|!r3bsource/neuland|!r3bsource/base|ext_h101*'
+          format-review: true
+      - name: Fail fast?!
+        if: steps.linter.outputs.clang-format-checks-failed > 0
+        run: exit 1
+        
+  clang-tidy:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        repos: [ fedora-latest ]
+        include:
+          - preset: default
+    container: 
+      image: yanzhaowang/r3bdev:${{ matrix.repos }}
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
+
+    - name: setup environments
+      run: |
+        echo "CCACHE_BASEDIR=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
+        echo "CCACHE_DIR=${GITHUB_WORKSPACE}/.ccache" >> $GITHUB_ENV
+        echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
+        echo "CCACHE_COMPRESSLEVEL=6" >> $GITHUB_ENV
+        echo "CONAN_HOME=${GITHUB_WORKSPACE}/.conan2" >> $GITHUB_ENV
+        echo "CXX=clang++" >> $GITHUB_ENV
+        echo "CC=clang" >> $GITHUB_ENV
+        echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
+        echo "NUM_THREADS=4" >> $GITHUB_ENV
+        sudo -H pip3 install -U conan
+
+    - name: load build cache
+      id: build-cache
+      uses: actions/cache/restore@v4
+      with:
+        path: | 
+          ${{ github.workspace }}/.ccache
+        key: r3b-build-cache-${{ matrix.repos }}
+
+    - name: load conan cache
+      id: conan-cache
+      uses: actions/cache/restore@v4
+      with:
+        path: | 
+          ${{ github.workspace }}/.conan2
+        key: r3b-conan-cache-${{ matrix.repos }}
+
+    - name: configure r3broot
+      uses: './.github/actions/r3bbuild-steps'
+      with:
+        build-needed: 'false'
+
+    - name: clang-tidy check
+      run: |
+        mkdir -p clang-tidy-result
+        git diff -U0 HEAD^ | python3 $PWD/util/clang-tidy-diff.py -p1 -path build -j4 -use-color \
+        -iregex '^(.*\/)(?!ext_)([^\/]*\.(cpp|cc|c\+\+|cxx|cl|hpp|hh|h|m|mm|inc))$' \
+        > clang-tidy-result/fixes.yml
+        cat clang-tidy-result/fixes.yml |\
+        sed -e 's/\x1b\[[0-9;]*m//g' |\
+        sed 's/\(^.*\):\([0-9]*\):\([0-9]*\): warning:/::warning file=\1,line=\2,col=\3::/' |\
+        sed 's/\(^.*\):\([0-9]*\):\([0-9]*\): error:/::error file=\1,line=\2,col=\3::/'
+        echo "WARN_NUM=$(sed -e 's/\x1b\[[0-9;]*m//g'  clang-tidy-result/fixes.yml | grep -w " warning:" | wc -l | xargs)" >> $GITHUB_ENV
+        echo "ERROR_NUM=$(sed -e 's/\x1b\[[0-9;]*m//g'  clang-tidy-result/fixes.yml | grep -w " error:" | wc -l | xargs)" >> $GITHUB_ENV
+
+    - name: clang-tidy results
+      run: |
+          if [ "${{ env.WARN_NUM }}" -eq "0" ] && [ "${{ env.ERROR_NUM }}" -eq "0" ]; then
+            echo "::notice::All clean, LGTM!"
+          else
+            cat clang-tidy-result/fixes.yml | sed -e 's/\x1b\[[0-9;]*mnote: \x1b\[0m/\x1b\[33mnote: \x1b\[0m/g'
+            echo "::notice::Clang-tidy generates ${{ env.WARN_NUM }} warnings and ${{ env.ERROR_NUM }} errors! Please fix them before being merged."
+            exit 1
+          fi
+      shell: bash
 
